service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-3
  memorySize: 128
  timeout: 6

functions:
  alexa-poc:
    handler: handler.alexa
    events:
      - http:
          method: post
          path: alexa
